### ISSUE TITLE
ERROR TypeError: x is not a function

### ISSUE THREAD

**Issue by konrad213** [vvscode/js--nightwatch-recorder#2]
Error while running [Test / test case]:
   
     TypeError: x is not a function
       at Object.test case (/Users/cex/Desktop/nightwatch/tests/test.js:11:29)
       at _combinedTickCallback (internal/process/next_tick.js:73:7)

Nightwatch does not recognize the variable x when I generate a script

**Comment by vvscode** [comment]
@konrad213  show your script, at least ))

**Comment by vvscode** [comment]
full listing for `/Users/cex/Desktop/nightwatch/tests/test.js`

**Comment by vvscode** [comment]
and scenario how to reproduce it ( how to generate the same script )

**Comment by konrad213** [comment]
module.exports = {
 'test case': function(client) {
   return client
     .resizeWindow(1806, 671)
     .url('https://www.google.es/')
     .waitForElementPresent("form[name=f] input[name='q']")
     .click("form[name=f] input[name='q']")
     .waitForElementPresent("input[name='q']")
     .setValue("input[name='q']", "some page")
     .waitForElementPresent(x("//a[normalize-space(text())='Herramientas']"))
     .click(x("//a[normalize-space(text())='Herramientas']"))
 }
};


and i run it in nightwatch

**Comment by konrad213** [comment]
and this is my nightwatch json
{
    "src_folders" : ["tests"],
   "custom_commands_path" : "reports",
  "custom_assertions_path" : "",
  "page_objects_path" : "",
  "globals_path" : "",
 
  "selenium" : {
    "start_process" : true,
    "server_path" : "bin/selenium-server-standalone-3.4.0.jar",
    "log_path" : "",
    "port" : 2112,
    "cli_args" : {
        "webdriver.chrome.driver" : "bin/chromedriver"
    }
  },
 
 
  "test_settings" : {
    "default" : {
      "globals" : {
                "waitForConditionTimeout" : 12000,
                "waitForConditionPollInterval" : 2000
            },
      "launch_url" : "http://localhost",
      "selenium_port"  : 2112,
      "selenium_host"  : "localhost",
      "silent": true,
      "screenshots" : {
        "enabled" : false,
        "path" : ""
      },
      "desiredCapabilities": {
        "browserName": "chrome",
        "marionette":true
      },
      "skip_testcases_on_fail": false
    }
 
  }
}

**Comment by vvscode** [comment]
@konrad213  I see, looks like problem in xpath selectors. Hope you have not much buggy scenarious. I'll provide update in few days and notify you

Thx for report

**Comment by konrad213** [comment]
Ok, thanks, I'll be waiting.

**Comment by vvscode** [comment]
@konrad213  please check fix from https://github.com/vvscode/js--nightwatch-recorder/issues/3

**Comment by konrad213** [comment]
when i run the test, nightwatch interprets xpath selectors as a comment
![image](https://cloud.githubusercontent.com/assets/18264614/26071690/30e523b4-39a9-11e7-8287-29b96550a543.png)

**Comment by vvscode** [comment]
Sorry, please fetch updates.
Should be fix ( at least for my scenario )

**Comment by vvscode** [comment]
@konrad213

**Comment by konrad213** [comment]
it works, thanks
