### ISSUE TITLE
customClick

### ISSUE THREAD

**Issue by wkocmann** [vvscode/js--nightwatch-recorder#6]
I was just wondering the output of the recorder is customClick but that is not part of vanilla Nightwatch.js 

What is behind the curtain of customClick()

**Comment by vvscode** [comment]
@wkocmann  I'm not sure about it

https://github.com/nightwatchjs/nightwatch/issues/1594#issuecomment-371752316 might be related

99% sure that it might be replaced with `.click`

**Comment by wkocmann** [comment]
Not quit the solution I was after but thanks
